-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 22:59:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(20) NULL,
  `cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`departamento` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produto` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` TEXT NULL,
  `preco` DOUBLE NULL,
  `estoque` INT NULL,
  `link_foto` VARCHAR(255) NULL,
  `departamento_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_produto_departamento_idx` (`departamento_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_produto_departamento`
    FOREIGN KEY (`departamento_codigo`)
    REFERENCES `ecommerce`.`departamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`endereco` (
  `num_seq` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(5) NULL,
  `logradouro` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(30) NULL,
  `cidade` VARCHAR(50) NULL,
  `cep` VARCHAR(10) NULL,
  `estado` VARCHAR(2) NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`num_seq`),
  INDEX `fk_endereco_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`pedido` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` DATE NULL,
  `valor_bruto` DOUBLE NULL,
  `status` VARCHAR(1) NULL,
  `desconto` DOUBLE NULL,
  `valor_final` DOUBLE NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_pedido_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`item_pedido` (
  `num_sequencial` INT NOT NULL,
  `pedido_numero` INT NOT NULL,
  `produto_codigo` INT NOT NULL,
  `quantidade` INT NULL,
  `valor_unitario` DOUBLE NULL,
  `valor_total` DOUBLE NULL,
  PRIMARY KEY (`num_sequencial`),
  INDEX `fk_pedido_has_produto_produto1_idx` (`produto_codigo` ASC) VISIBLE,
  INDEX `fk_pedido_has_produto_pedido1_idx` (`pedido_numero` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_produto_pedido1`
    FOREIGN KEY (`pedido_numero`)
    REFERENCES `ecommerce`.`pedido` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_produto_produto1`
    FOREIGN KEY (`produto_codigo`)
    REFERENCES `ecommerce`.`produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
